### ISSUE TITLE
Language switcher links to index but not current page

### ISSUE THREAD

**Issue by stellala** [justmover/mevcc-wp-src#4] opened 2020-07-10 04:40 UTC
Buttons of language switcher plugin cannot be placed as current design,
to maintain the layout and be functional, 
the language switcher on the right top of menu links to "/" for Chinese and "/en" for English,
so every time switching language, user will be directed to index page but not staying at current page (e.g. blog) 

To solve the issue, we may
#1 change layout
#2 add shortcode to custom links on right top

**Comment by littlepine** [comment] 2020-07-10 07:52
I have tested the news and it can't reproduce the problem.
The current behaviour when current don't have translation:
Stay in current page with default language (zh).

Here is the video on latest source:
[2020-07-10 15-50-33.mp4.zip](https://github.com/justmover/mevcc-wp-src/files/4901763/2020-07-10.15-50-33.mp4.zip)

**Comment by littlepine** [comment] 2020-07-10 08:17
The language switcher on header is just dummy, please remove it.

As the original plugin works fine, closing this issue.
![WhatsApp Image 2020-07-10 at 4 09 24 PM](https://user-images.githubusercontent.com/2181304/87132611-b68a8300-c2c8-11ea-9725-6f560743c406.jpeg)

**Closed by littlepine** 2020-07-10 08:17 UTC
